server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: parking-space-service
          uri: lb://parking-space-service
          predicates:
            - Path=/parking/**
        - id: vehicle-service
          uri: lb://vehicle-service
          predicates:
            - Path=/vehicles/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/payments/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
