server:
  port: 8083

spring:
  application:
    name: vehicle-service
  datasource:
    url: jdbc:mysql://localhost:3306/spms
    username: root
    password: your_password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
